export interface Country {
    label: string;
    value: string;
    flag: string;
}

export const countries: Country[] = [
    { label: "Keine Angabe", value: "", flag: "🏳️" },
    { label: "Deutschland", value: "Deutschland", flag: "🇩🇪" },
    { label: "Österreich", value: "Österreich", flag: "🇦🇹" },
    { label: "Schweiz", value: "Schweiz", flag: "🇨🇭" },
    // Europa
    { label: "Niederlande", value: "Niederlande", flag: "🇳🇱" },
    { label: "Belgien", value: "Belgien", flag: "🇧🇪" },
    { label: "Luxemburg", value: "Luxemburg", flag: "🇱🇺" },
    { label: "Frankreich", value: "Frankreich", flag: "🇫🇷" },
    { label: "Italien", value: "Italien", flag: "🇮🇹" },
    { label: "Spanien", value: "Spanien", flag: "🇪🇸" },
    { label: "Portugal", value: "Portugal", flag: "🇵🇹" },
    { label: "Polen", value: "Polen", flag: "🇵🇱" },
    { label: "Tschechien", value: "Tschechien", flag: "🇨🇿" },
    { label: "Dänemark", value: "Dänemark", flag: "🇩🇰" },
    { label: "Schweden", value: "Schweden", flag: "🇸🇪" },
    { label: "Norwegen", value: "Norwegen", flag: "🇳🇴" },
    { label: "Finnland", value: "Finnland", flag: "🇫🇮" },
    { label: "Vereinigtes Königreich", value: "Vereinigtes Königreich", flag: "🇬🇧" },
    { label: "Irland", value: "Irland", flag: "🇮🇪" },
    { label: "Griechenland", value: "Griechenland", flag: "🇬🇷" },
    { label: "Kroatien", value: "Kroatien", flag: "🇭🇷" },
    { label: "Ungarn", value: "Ungarn", flag: "🇭🇺" },
    { label: "Rumänien", value: "Rumänien", flag: "🇷🇴" },
    { label: "Bulgarien", value: "Bulgarien", flag: "🇧🇬" },
    { label: "Slowakei", value: "Slowakei", flag: "🇸🇰" },
    { label: "Slowenien", value: "Slowenien", flag: "🇸🇮" },
    { label: "Estland", value: "Estland", flag: "🇪🇪" },
    { label: "Lettland", value: "Lettland", flag: "🇱🇻" },
    { label: "Litauen", value: "Litauen", flag: "🇱🇹" },
    { label: "Ukraine", value: "Ukraine", flag: "🇺🇦" },
    { label: "Russland", value: "Russland", flag: "🇷🇺" },
    // Asien
    { label: "China", value: "China", flag: "🇨🇳" },
    { label: "Japan", value: "Japan", flag: "🇯🇵" },
    { label: "Südkorea", value: "Südkorea", flag: "🇰🇷" },
    { label: "Indien", value: "Indien", flag: "🇮🇳" },
    { label: "Thailand", value: "Thailand", flag: "🇹🇭" },
    { label: "Vietnam", value: "Vietnam", flag: "🇻🇳" },
    { label: "Indonesien", value: "Indonesien", flag: "🇮🇩" },
    { label: "Malaysia", value: "Malaysia", flag: "🇲🇾" },
    { label: "Philippinen", value: "Philippinen", flag: "🇵🇭" },
    { label: "Singapur", value: "Singapur", flag: "🇸🇬" },
    { label: "Taiwan", value: "Taiwan", flag: "🇹🇼" },
    { label: "Israel", value: "Israel", flag: "🇮🇱" },
    { label: "Türkei", value: "Türkei", flag: "🇹🇷" },
    { label: "Saudi-Arabien", value: "Saudi-Arabien", flag: "🇸🇦" },
    { label: "Ver. Arabische Emirate", value: "Ver. Arabische Emirate", flag: "🇦🇪" },
    { label: "Kasachstan", value: "Kasachstan", flag: "🇰🇿" },
    { label: "Pakistan", value: "Pakistan", flag: "🇵🇰" },
    // Amerika
    { label: "USA", value: "USA", flag: "🇺🇸" },
    { label: "Kanada", value: "Kanada", flag: "🇨🇦" },
    { label: "Mexiko", value: "Mexiko", flag: "🇲🇽" },
    { label: "Brasilien", value: "Brasilien", flag: "🇧🇷" },
    { label: "Argentinien", value: "Argentinien", flag: "🇦🇷" },
    { label: "Kolumbien", value: "Kolumbien", flag: "🇨🇴" },
    { label: "Chile", value: "Chile", flag: "🇨🇱" },
    // Afrika
    { label: "Ägypten", value: "Ägypten", flag: "🇪🇬" },
    { label: "Südafrika", value: "Südafrika", flag: "🇿🇦" },
    { label: "Marokko", value: "Marokko", flag: "🇲🇦" },
    { label: "Nigeria", value: "Nigeria", flag: "🇳🇬" },
    { label: "Kenia", value: "Kenia", flag: "🇰🇪" },
    // Ozeanien
    { label: "Australien", value: "Australien", flag: "🇦🇺" },
    { label: "Neuseeland", value: "Neuseeland", flag: "🇳🇿" },
];
